import Foundation
import CoreGraphics  // Config.swift's CGPoint Codable conformance + favicon PNGs
import ImageIO
import UniformTypeIdentifiers

/// Exports the pet's frame matrices and built-in theme palettes to
/// `docs/sprites.js` so the website's canvas chestnut renders from the same
/// data as the app (no image assets on the site either). `make site`
/// regenerates; `make check` fails if the committed file has drifted.
///
/// Output is a plain script (not JSON fetched at runtime) so the page also
/// works from file:// during local preview.
enum WebSpriteGenerator {
    static func main() throws {
        let outputPath = CommandLine.arguments.count > 1
            ? CommandLine.arguments[1] : "docs/sprites.js"
        // Makefile VERSION, shown by the site's menu re-creation ("Chestnut x.y.z").
        let version = CommandLine.arguments.count > 2
            ? CommandLine.arguments[2] : "dev"

        var out = """
        // Generated by `make site` from Sources/Chestnut/Pet/{PetFrames,SpriteTheme}.swift.
        // Do not edit by hand — change the Swift sources and rerun `make site`.
        window.CHESTNUT_SPRITES = {
          "version": "\(version)",
          "gridWidth": \(PetFrames.gridWidth),
          "gridHeight": \(PetFrames.gridHeight),
          "frames": {

        """
        for (index, variant) in PetFrames.bodyVariants.enumerated() {
            let comma = index == PetFrames.bodyVariants.count - 1 ? "" : ","
            out += "    \"\(variant.name)\": \(rowsLiteral(variant.rows, indent: 4))\(comma)\n"
        }
        out += """
          },
          "zPixel": \(rowsLiteral(PetFrames.zPixel, indent: 2)),
          "themes": [

        """
        for (index, theme) in SpriteTheme.builtIn.enumerated() {
            let comma = index == SpriteTheme.builtIn.count - 1 ? "" : ","
            let roles = theme.palette.keys.sorted()
                .map { role -> String in
                    let c = theme.palette[role]!
                    let hex = String(format: "#%02X%02X%02X%02X", c.r, c.g, c.b, c.a)
                    return "\"\(role)\": \"\(hex)\""
                }
                .joined(separator: ", ")
            out += """
                { "id": "\(theme.id)", "title": "\(theme.title)",
                  "palette": { \(roles) } }\(comma)

            """
        }
        out += """
          ]
        };

        """

        try out.write(toFile: outputPath, atomically: true, encoding: .utf8)
        print("wrote \(outputPath)")

        let dir = (outputPath as NSString).deletingLastPathComponent
        try writeFavicons(into: dir.isEmpty ? "." : dir)
    }

    // MARK: - Favicons

    /// Same framing as `make icon` (Scripts/generate-icon.swift): the peek
    /// frame in Obsidian Night on the squircle gradient. favicon.svg is
    /// deterministic text, so `make check` drift-guards it; the PNGs
    /// (fallback favicon + apple-touch-icon) are regenerated by `make site`
    /// but not diffed — image encoders may vary across OS releases.
    private static let bgBottom: (r: UInt8, g: UInt8, b: UInt8) = (41, 36, 69)
    private static let bgTop: (r: UInt8, g: UInt8, b: UInt8) = (61, 54, 97)

    private static func writeFavicons(into dir: String) throws {
        let palette = SpriteTheme.obsidianNight.palette
        let rows = PetFrames.peek
        try writeFaviconSVG(rows: rows, palette: palette, to: "\(dir)/favicon.svg")
        try writeFaviconPNG(
            rows: rows, palette: palette, size: 32, squircle: true,
            to: "\(dir)/favicon.png"
        )
        // Full-bleed: iOS applies its own corner mask to touch icons.
        try writeFaviconPNG(
            rows: rows, palette: palette, size: 180, squircle: false,
            to: "\(dir)/apple-touch-icon.png"
        )
    }

    private static func writeFaviconSVG(
        rows: [String], palette: [Character: SpriteTheme.RGBA], to path: String
    ) throws {
        let hex = { (r: UInt8, g: UInt8, b: UInt8) in
            String(format: "#%02X%02X%02X", r, g, b)
        }
        var svg = """
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
        <defs><linearGradient id="bg" x1="0" y1="1" x2="0" y2="0">
        <stop offset="0" stop-color="\(hex(bgBottom.r, bgBottom.g, bgBottom.b))"/>
        <stop offset="1" stop-color="\(hex(bgTop.r, bgTop.g, bgTop.b))"/>
        </linearGradient></defs>
        <rect width="32" height="32" rx="7.2" fill="url(#bg)"/>

        """
        // Sprite centered in the 32-grid; horizontal same-color runs merged.
        let offsetX = (32 - rows[0].count) / 2
        let offsetY = (32 - rows.count) / 2
        for (y, row) in rows.enumerated() {
            let chars = Array(row)
            var x = 0
            while x < chars.count {
                var run = 1
                while x + run < chars.count && chars[x + run] == chars[x] { run += 1 }
                if let c = palette[chars[x]], c.a != 0 {
                    let opacity = c.a == 255
                        ? "" : String(format: " fill-opacity=\"%.3f\"", Double(c.a) / 255)
                    svg += "<rect x=\"\(x + offsetX)\" y=\"\(y + offsetY)\" "
                        + "width=\"\(run)\" height=\"1\" "
                        + "fill=\"\(hex(c.r, c.g, c.b))\"\(opacity)/>\n"
                }
                x += run
            }
        }
        svg += "</svg>\n"
        try svg.write(toFile: path, atomically: true, encoding: .utf8)
        print("wrote \(path)")
    }

    private static func writeFaviconPNG(
        rows: [String], palette: [Character: SpriteTheme.RGBA],
        size: Int, squircle: Bool, to path: String
    ) throws {
        let pixelScale = max(1, size / rows[0].count)
        let spriteW = rows[0].count * pixelScale
        let spriteH = rows.count * pixelScale

        var bytes = [UInt8]()
        bytes.reserveCapacity(spriteW * spriteH * 4)
        for row in rows {
            var pixelRow = [UInt8]()
            for ch in row {
                let c = palette[ch]!
                for _ in 0..<pixelScale {
                    pixelRow.append(contentsOf: [c.r, c.g, c.b, c.a])
                }
            }
            for _ in 0..<pixelScale { bytes.append(contentsOf: pixelRow) }
        }
        let provider = CGDataProvider(data: Data(bytes) as CFData)!
        let sprite = CGImage(
            width: spriteW, height: spriteH,
            bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: spriteW * 4,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
            provider: provider, decode: nil,
            shouldInterpolate: false, intent: .defaultIntent
        )!

        let ctx = CGContext(
            data: nil, width: size, height: size,
            bitsPerComponent: 8, bytesPerRow: size * 4,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        )!
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        ctx.saveGState()
        if squircle {
            let radius = Double(size) * 0.225
            ctx.addPath(CGPath(
                roundedRect: CGRect(x: 0, y: 0, width: size, height: size),
                cornerWidth: radius, cornerHeight: radius, transform: nil
            ))
            ctx.clip()
        }
        let gradient = CGGradient(
            colorsSpace: colorSpace,
            colors: [
                CGColor(colorSpace: colorSpace, components: [
                    Double(bgBottom.r) / 255, Double(bgBottom.g) / 255, Double(bgBottom.b) / 255, 1,
                ])!,
                CGColor(colorSpace: colorSpace, components: [
                    Double(bgTop.r) / 255, Double(bgTop.g) / 255, Double(bgTop.b) / 255, 1,
                ])!,
            ] as CFArray,
            locations: [0, 1]
        )!
        ctx.drawLinearGradient(
            gradient, start: CGPoint(x: 0, y: 0), end: CGPoint(x: 0, y: size), options: []
        )
        ctx.restoreGState()

        ctx.interpolationQuality = .none
        ctx.draw(sprite, in: CGRect(
            x: (size - spriteW) / 2, y: (size - spriteH) / 2,
            width: spriteW, height: spriteH
        ))

        let url = URL(fileURLWithPath: path) as CFURL
        let dest = CGImageDestinationCreateWithURL(url, UTType.png.identifier as CFString, 1, nil)!
        CGImageDestinationAddImage(dest, ctx.makeImage()!, nil)
        CGImageDestinationFinalize(dest)
        print("wrote \(path)")
    }

    /// Frame rows as a JS string array, one row per line (readable diffs).
    private static func rowsLiteral(_ rows: [String], indent: Int) -> String {
        let pad = String(repeating: " ", count: indent)
        let body = rows.map { "\(pad)  \"\($0)\"" }.joined(separator: ",\n")
        return "[\n\(body)\n\(pad)]"
    }
}

@main enum Tool {
    static func main() throws {
        try WebSpriteGenerator.main()
    }
}
